### ISSUE TITLE
Step 2: The TaskManager Class

### ISSUE THREAD

**Issue by AGROYGBV** [BitContext/team-awesome-project#19]
Create a TaskManager class in js/taskManager.js

Within the constructor of the TaskManager class, initialize a this.tasks property on the class equal to an empty array.

Test Your Code!
Now is a good chance to test your code, head over to js/index.js and do the following

Initialize a new instance of TaskManager
console.log() the tasks property

**Comment by hebatullah2** [comment]
fixed
